python:
  - 2.7
  - 3.6
c_compiler:      # [win]
  - vs2008       # [win]
  - vs2015       # [win]
cxx_compiler:    # [win]
  - vs2008       # [win]
  - vs2015       # [win]
zip_keys:
  -
    - python
    - c_compiler    # [win]
    - cxx_compiler  # [win]
